projects:
  - name: Messina Inclusiva
    description: |
      Messina Inclusiva nasce dalla misura PNRR 1.4.2. Citizen Inclusion volto a migliorare l'accessibilità dei servizi digitali.
    documents:
#      - messinainclusiva-lgdesignaccessibilita-docs
