publisher:
  name: Comune di Messina
  description: |
    Il Comune di Messina è un ente pubblico territoriale che rappresenta, amministra e cura gli interessi della comunità locale della città di Messina.
  github_organization_url: github.com/ComuneDiMessina
  website: https://www.comune.messina.it
#  logo: assets/images/logo.svg
